### ISSUE TITLE
Implement ValidationResult statuses

### ISSUE THREAD

**Issue by rechkalov** [2gis/nuclear-river#101]
Проблема: сейчас в зависимости от контекста вызова проверки критичность её срабатывания может различаться.

Согласно https://confluence.2gis.ru/pages/viewpage.action?pageId=51577357 есть 4 контекста проверок, каждая проверка для каждого контекста может выдавать 3 различных результата. 
Итого, возможен 81 вариант, не так уж много. Значит, вполне подойдёт решение с целочисленным полем статуса, который будет интерпретироваться Querying **со знанием контекста** проверки (отсюда требование передавать не только ключ для поиска сообщений - период, город, и т. п., но и контекст, в котором запрашиваются результаты.

Кроме того, **как правило**, одна проверка может выдавать только одну комбинацию. Есть исключения, например LinkingObjectsOrderValidationRule выдаёт Warning при единичной и Error при массовых, за исключением случаев, когда проверятся позиция с типом объекта привязки CategoryMultipleAsterix - тогда уровень Info. Это усложняет проверку и может служить формальным поводом разбить её на два независимых ValidationResult - проблемой является только то, что выборка и критерии запуска обоих полученных проверок будет абсолютно одинаковой, отличие будет лишь в одном условии.

Если всё-таки принять утверждение "одна проверка может иметь только один статус" то достаточно будет сопоставления проверок и их статусов, причём это сопоставление может быть изменено без перезапуска репликации. Вопрос, нужно ли это.

Можно положить расшифровку этих статусов прямо в таблицу вида 

|Status|Single|Mass|MassPrerelease|MassRelease|
|------|------|----|--------------|-----------|
|...|
| 57|Error|Info|Waring|Info|
|...|

Можно не заморачиваться с этим, статус 57 можно прочитать в троичной системе (2010), что в свою очередь легко мапится на Single = Error, Mass = Info, MassPrerelease = Waring, MassRelease = Info.

**Comment by rechkalov** [comment]
Может быть, неудачной является базовая модель и возможно более правильное решение?

Единичная проверка обычно вызывается для заказов в статусах, отличных от "одобрено" (хотя возможна и для одобренных, но кто этим пользуется?). Массовая проверка, наоборот, проверяет одобренные, она предназначена для выходящих в выпуск заказов. Означает ли это, что критичность ошибок зависит от статуса заказа, а контекст вообще ни при чём и от самого понятия можно/нужно избавиться?

Если предположить, что статусная модель должна быть другой, а ошибки в проверках блокируют перевод в следующий статус?

Например, заказ в статусе "На оформлении" проверяется на заполненность обязательных полей. Если есть ошибки - перевод в "На утверждении" невозможен. Хорошо. Но ведь оформленный заказ переводить никуда не надо, а в нём может возникнуть ошибка (даже если заказ не менялся), блокирующая сборку. Примеры таких ошибок - не хватает денег или сопутствующие-запрещённые. Статус менять уже не надо, а в сборку он попасть не может. Нужен статус "готов к сборке", который будет откачен после сборки на "одобрен"?

На оформлении -> На утверждении -> Одобрен -> Готов к сборке -> Одобрен

Как быть с теми проверками, которые группируют заказы по какому-либо признаку, например, по фирме? Должно получиться, что в группе одобренные заказы могут получить сообщения одного уровня критичности (низкого, им-то ничего не мешает), а на оформлении - другого. Выглядит логично. И при этом, например, если досрочно расторгнут заказ с основной позицией, то прочие заказы этой фирмы получат ошибку. Хотя, стоп. Они уже "готовы к сборке" - откуда ошибки? Если не готовы, то кто их снял? Получается, что если нужно снять статус "готов к сборке" с одного заказа - то автоматом слетают все заказы города.

При этом становится ненужным рубильник, который блокирует редактирование заказов во время сборки - нельзя редактировать только "готовые к сборке" заказы. Кажется, и интеграция с "экспортом" должна упроститься.

В целом выглядит более согласованным решением, чем завязка на контексты вызова проверок, но нужна аналитика и более тесная связь с erm.

В качестве разминки можно попробовать проработать эту модель для наших первых трёх проверок без изменений статусов в erm.

**Comment by denisivan0v** [comment]
copied to https://github.com/2gis/nuclear-river-validation-rules/issues/3
