### ISSUE TITLE
Проверка на сопутствие-запрещение

### ISSUE THREAD

**Issue by rechkalov** [2gis/nuclear-river#103]
Для прайс-листов, у позиций которых более одной AssociatedPositionsGroup должно выводиться предупреждение.

Для заказов в статусе "на расторжении", если они содержат основную позицию для остающихся одобренными заказов и среди одобренных нет другой основной позиции должно выводиться предупреждение.

Для заказов, которые содержат запрещённые друг к другу позиции должна выводиться ошибка (ошибка не должна выводиться, для одобренного заказа, если запрещённая позиция находится в не одобренном заказе)

Для заказов, которые содержат пару сопутствующая-запрещённая с совпадающими объектами привязки и указанным ObjectBindingType.Different должна выводиться ошибка // Запрещение через сопутствующие позиции?!

Для заказа, в котором есть сопутствующая позиция и нет основной должна выводиться ошибка.

Для заказа, в котором есть сопутствующая позиция и есть основная, но не удовлетворено условие ObjectBindingType.Match должна выводиться ошибка.

**Comment by denisivan0v** [comment]
copied to https://github.com/2gis/nuclear-river-validation-rules/issues/4
