### ISSUE TITLE
Proposal for in-memory joins

### ISSUE THREAD

**Issue by denisivan0v** [2gis/nuclear-river#11]
We need to be able to join data from different data storages (different source systems), but contexts description shouldn't change.

Can it be done with special `IQuery` implementation?

**Comment by rechkalov** [comment]
Сначала нужно определиться какие именно препятствия тому, чтобы тупо выгрести оба множества в память (или сливать их потоками, отсортировав по ключу).

У нас после слияния накладываются фильтры, которые (если их пробросить на исходные множества - это задача техническая, а значит - решаемая) могут существенно сузить мощность одного из них или обоих.

Прикинем стратегии поведения в зависимости от размера множеств после фильтрации

A | B | Предполагаемый способ
----|----|----
1 | 1 | итерировать оба множества
1 | 1000 | выполнить фильтрацию второго на основании выборки из первого
1 | ∞ | выполнить фильтрацию второго на основании выборки из первого
1000 | 1000 | итерировать оба множества
1000 | ∞ | выполнить фильтрацию второго на основании части выборки из первого
∞ | ∞ | итерировать оба множества

Для реализации такого подхода требуется, чтобы в хранилищах были эффективно реализованы подсчёт числа элементов и фильтрация.

Получается, если мощности множеств сравнимы, то итерируем их. Если мощность одного значительно меньше - используем его для фильтрации второго по ключу.

Теперь о том, где это реализовывать.

В `IQuery` - не вижу возможности. Думаю, должно быть описано в конкретных экземплярах `MapSpecification`. Что-то типа

```c#
new MapSpecification<IQuery, IQueryable<T>>(q =>
    {
        Queryable.Join(q.For<SourceA>(), q.For<SourceB>(), a => a.key, b => b.key, (a, b) => new { a, b });
    });
```

Но тут проблема в том, что для результата будет использован `IQueryProvider` взятый из `q.For<SourceA>() `, а аналогичный для поставщик для SourceB будет потерян (см [реализацию](http://referencesource.microsoft.com/#System.Core/System/Linq/IQueryable.cs,61ae4d468e97dbdf,references)). Поэтому требуется своя реализация поставщика, которая сохранит оба поставщика и по возможности будет передавать фильтры им, а не применять их на результат join.

Полноценную реализацию, с поддержкой всех возможностей linq, сделать трудно, но минимально удовлетворяющую нашим потребностям - вполне возможно.

PS. Сложно поверить, что такой задачи никогда не возникало, но краткий поиск не

**Comment by denisivan0v** [comment]
There is an interesting article on the topic http://db.cs.duke.edu/papers/2006-xy-sjoinbook.pdf

**Comment by denisivan0v** [comment]
And some some more articles:

* [The Log: What every software engineer should know about real-time data's unifying abstraction](https://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying)
* [Stream processing, Event sourcing, Reactive, CEP… and making sense of it all](http://www.confluent.io/blog/making-sense-of-stream-processing/)

It would be also interesting to take a look at http://samza.apache.org/learn/documentation/0.10/

**Comment by denisivan0v** [comment]
Library's code for in-memory joins is here https://github.com/2gis/nuclear-join

**Comment by rechkalov** [comment]
Due to some difficulties, this task will be deferred.

Found dificulties:
* Technical task with large cost: translate filter expression that applied to join result to multiple filter expressions than can be applied to joined data sources - to reduce data transmitted by network and memory consumption.
* Limitation: when needed to sort joined sequence or apply another join - you must get all data in memory.

**Comment by rechkalov** [comment]
PS. Here is no relation to stream joins.

**Comment by denisivan0v** [comment]
I'm closing this issue for now. It'll be reopened if we decide to continue this work
