### ISSUE TITLE
Группа проверок на логическую целостность

### ISSUE THREAD

**Issue by rechkalov** [2gis/nuclear-river#118]
#### ThemePositionCountValidationRule (2)
- Есть период. Есть Scope.
- Для заказов и проектов, с превышением числа проданных тематик, должна выводиться ошибка.
  - "Слишком много продаж в тематику {0}. Продано {1} позиций вместо {2} возможных"

#### AdvertisementForCategoryAmountOrderValidationRule (2)
- Есть период. Есть Scope.
- Для проектов, с превышением продаж определённой номенклатуры в рубрику, должна выводиться ошибка в массовой и предупреждение в единичной.
  - "В рубрику {0} заказано слишком много объявлений: Заказано {1}, допустимо не более {2}"
  
#### FirmsOrderValidationRule (1)
- Не запускается при ручной массовой проверке, и при смене статуса (за исключением "на оформлении")
- Для заказов, к которым привязана неактуальная фирма, должна выводиться ошибка.
  - "Фирма {0} удалена"
  - "Фирма {0} скрыта навсегда"
  - "Фирма {0} скрыта до выяснения"
  
#### LinkingObjectsOrderValidationRule (4)
- Не запускается при ручной массовой проверке, и при смене статуса (за исключением "на оформлении")
- Для заказов, к которым привязан неактульный адрес, должна выводиться ошибка.
  - "В позиции {0} адрес фирмы {1} скрыт навсегда"
  - "В позиции {0} адрес фирмы {1} скрыт до выяснения"
  - "В позиции {0} найден неактивный адрес {1}"
  - "В позиции {0} найден адрес {1}, не принадлежащий фирме заказа"
- Для заказов, к которым привязана неактуальная рубрика должно выводиться сообщение
  - "В позиции {0} найдена неактивная рубрика {1}" - ошибка
  - "В позиции {0} найдена рубрика {1}, не принадлежащая фирме заказа" - предупреждение в единичной, ошибка в массовой. иногда - информация. Вероятно, отдельная проверка или несколько.
- Для заказов с продажами в рубрику адреса, к которым привязана рубрика не принадлежащая адресу, должно выводиться предупреждение в единичной, ошибка в массовой.
  - "В позиции {0} найдена рубрика {1}, не принадлежащая адресу {2}"
  
#### DistributionDatesOrderValidationRule (1)
- Не запускается при ручной массовой проверке, и при смене статуса (за исключением "на оформлении")
- Для заказов, у которых даты размещения нарушают соглашение, должна выводиться ошибка.
  - "Указана некорректная дата начала размещения"
  - "Указана некорректная дата окончания размещения"
  
#### BargainEndDateOrderValidationRule (1)
- Запускается только для заказов "на оформлении"
- Для заказов, у профиля (любого из) юрлица клиента которого указана дата договора меньшая чем дата подписания заказа, должно выводиться информационное сообщение.
  - "У юр. лица клиента, в профиле {0} указан договор с датой окончания действия раньше даты подписания заказа"

#### BillsSumsOrderValidationRule (2)
- Запускается только для заказов "на оформлении"
- Для заказов, с ненулевой с суммой заказа, должна выводиться ошибка
  - "Для заказа необходимо сформировать счета"
- Для заказов, у которых сумма по счетам не совпадает с суммой заказа, должна выводиться ошибка
  - "Сумма по счетам не совпадает с планируемой суммой заказа"
- Для заказов, у которых период размещения не совпадает с датами в счетах на оплату, должна выводиться ошибка
  - "Период размещения, указанный в заказе и в счете не совпадают"
  
#### BargainOutOfDateOrderValidationRule -> BargainAndOrderSignDatesValidationRule (1)
- Запускается только для заказов "на оформлении"
- Для заказов, у которых дата подписания ранее даты подписания договора, должна выводиться ошибка.
  - "Договор не может иметь дату подписания позднее даты подписания заказа"
  
#### RequiredFieldsNotEmptyOrderValidationRule (1)
- Не запускается при ручной массовой проверке, и при смене статуса (за исключением "на оформлении")
- Для заказов, у которых не заполнено одно из одз полей, должна выводиться ошибка.
  - "Необходимо заполнить все обязательные для заполнения поля: {0}"
  
#### LegalPersonProfilesOrderValidationRule (1)
- Запускается только для заказов "на оформлении"
- Для заказов, у юрлиц которых нет ни одного профиля, должна выводиться ошибка.
  - "У юр. лица клиента отсутствует профиль"
  
#### WarrantyEndDateOrderValidationRule (1)
- Запускается только для заказов "на оформлении"
- Для заказов, у профиля (любого из) юрлица клиента которого указана дата доверенности меньшая чем дата подписания заказа, должно выводиться информационное сообщение.
  - "У юр. лица клиента, в профиле {0} указана доверенность с датой окончания действия раньше даты подписания заказа"
  
#### OrderHasAtLeastOnePositionOrderValidationRule (1)
- Не запускается при ручной массовой проверке, и при смене статуса (за исключением "на оформлении")
- Для заказов, без позиций, должна выводиться ошибка.
  - "Заказ не содержит ни одной позиции"
  
#### OrdersAndBargainsScansExistOrderValidationRule (1)
- Запускается только для заказов "на оформлении"
- Для заказов, у которых отсутствует скан бланка заказа, должно выводиться предупреждение.
  - "Отсутствует сканированная копия Бланка заказа"
- Для заказов, у которых есть договор и отсутствет его скан, должно выводиться предупреждение.
  - "Отсутствует сканированная копия договора"

**Comment by denisivan0v** [comment]
copied to https://github.com/2gis/nuclear-river-validation-rules/issues/5
