### ISSUE TITLE
Create metadata descriptions/MapSpecs to (re)construct aggregates using facts

### ISSUE THREAD

**Issue by denisivan0v** [2gis/nuclear-river#20]
Given aggregates structure defined in #7 now we need to find out how to (re)construct them using data in [facts storage](https://2gis.gitbooks.io/nuclear-river/content/en/terms.html) and create m[etadata descriptions](https://2gis.gitbooks.io/nuclear-river/content/en/terms.html) for it

**Comment by denisivan0v** [comment]
@maximpashuk any updates here? will you create a PR?

**Comment by maximpashuk** [comment]
This issue is linked with #21, fixing #21 is affecting on #20 also.
So I think they should be reviewed together.

**Comment by denisivan0v** [comment]
Ok. Can you mention this issue in commits (with #20 token)? It'll clarify the progress
