### ISSUE TITLE
Link to nuget.2gis.local

### ISSUE THREAD

**Issue by 13h3r** [2gis/nuclear-river#55]
There is a link to `nuget.2gis.local` in nuget config.

**Comment by denisivan0v** [comment]
Yes, we have dependencies that can be accessible only localy.
But we have [public CI-server] (http://opensource-ci.2gis.ru/view/NuClear/job/nuclear-river) where all binaries can be built

**Comment by 13h3r** [comment]
Will it work for me if I do checkout the project and build it from outside?

**Comment by maximpashuk** [comment]
@13h3r will work in release 1.0.3

**Comment by denisivan0v** [comment]
:+1:
