### ISSUE TITLE
Event context unification (ETL phase 2)

### ISSUE THREAD

**Issue by denisivan0v** [2gis/nuclear-river#8]
@rechkalov, your proposals are welcomed

**Comment by rechkalov** [comment]
Сейчас в сущность PerformedOperationFinalProcessing так или иначе сериализуются различные реализации IOperation. И если тип операции логично ложится в OperationId, то с остальными полями сложнее.

Для Initialize\Recalculate\DestroyAggregateOperation поля типа и идентификатора агрегата кладутся в EntityType\EntityId.

Для RecalculateStatisticsOperation используется xml-поле Context, куда помещается либо идентфикатор проекта (для пересчёта проекта целиком), либо идентификаторы проекта и рубрики (для пересчёта только одной рубрики в проекте).

На горизонте появляются операции VR и чтобы всё ещё сильнее не запутать, предлагаю следующие изменения:

Видится, что дополнительные поля в операции отвечают на вопрос "что именно" (требуется пересчитать, создать или удалить), поэтому можно выделить сущность, отвечающую на этот вопрос и тогда понятие операции будет состоять из пары ("что сделать", "с чем именно").

Новая сущность по функции схожа с FindSpecification, но должна быть легко сериализуема, бонусом можно получить независимость от конкретных clr-типов.

Простейший вариант - тип+идентификатор - для агрегатов.
Сложнее для статистики - по неключевому полю ProjectId или паре (ProjectId, CategoryId)
Вероятно, для VR потребуются более сложные случаи. Например, заказы по номенклатурной позиции. Учитывая, что они напрямую не связаны, потребуется или объяснить join внутри запроса, или просто понимать такие "спецификации" - я склоняюсь ко второму варианту. К чему-то похожему мы пришли в List-сервисах, когда есть название фильтра и его параметры, а сервис уже сам знает какие join нужно выполнить.

Примерный список работ:
* POCO-класс(ы) (как назвать? Identity, Filter, Find - всё уже заезжено)
* их (де)сериализация в xml (сервис, подключаемые с новыми контекстами правила)
* их преобразование в FindSpecification (сервис, подключаемые с новыми контекстами правила)

**Comment by maximpashuk** [comment]
Концепт хороший, думаю можно брать в реализацию

**Comment by denisivan0v** [comment]
There is an interesting article on the topic http://db.cs.duke.edu/papers/2006-xy-sjoinbook.pdf

**Comment by rechkalov** [comment]
Пошёл по пути записи некоторого дерева выражений (предикатов), с возможностью по каждому построить Expression и описанием этого дела в MetadataSource

```
<context>
  <entity Type="Order">
    <predicate id="and" >
      <predicate id="HasIdentifier" value="5" />
      <predicate id="HasIdentifier" value="9" />
      <predicate id="HasPropertyValue" property="WorkflowStepId" value="1" />
      <predicate id="Фиолетовый в крапинку" />
    </predicate>
  </entity>
</context>
```

однако мы для оптимизации группируем запросы. Просто объединить предикаты через "или" - не сложно, но приведёт к значительному усложнению запросов.

Поэтому структуру пришлось упростить, отказавшись от произвольных элементов.

```
<context>
  <predicate id="HasIdentifier" entity="146" value="5" />
</context>
```

Теперь их можно группировать (учитывая, что для одного типа операции есть фиксированный набор предикатов). При этом специальный MetadataSource получился не нужен.

**Comment by denisivan0v** [comment]
Стоит ли `id` заменить на 'type` для сохранения семантики? То есть, как-то так:

```
<context>
  <predicate type="HasIdentifier" entity="146" value="5" />
</context>
```

**Comment by denisivan0v** [comment]
Еще одна мысль. Нам стоит привести терминологию в соответствие с общепринятой. По факту, `XXXAggregateOperation ` - это команда для выполнения какой-либо операции, а не сама операция. Вот тут https://cqrs.files.wordpress.com/2010/11/cqrs_documents.pdf есть полное описание, можно взять за основу

**Comment by rechkalov** [comment]
> По факту, XXXAggregateOperation - это команда для выполнения какой-либо операции, а не сама операция. 

На самом деле это достаточно неоднозначный вопрос: я до сих пор трактовал это как запись в логе о произошедшей в мастер-системе операции.

> Стоит ли id заменить на type для сохранения семантики

Может, стоит (хотя я не совсем понимаю, при чём тут тип). А может (с целью экономии запаса букв) стоит вообще обойтись чем-нибудь вроде

```
<context>
  <HasIdentifier entity="146" value="5" />
</context>
```

**Comment by denisivan0v** [comment]
> это достаточно неоднозначный вопрос

Очень **важно** прийти к однозначному пониманию. Вот копипаст из [той статьи](https://cqrs.files.wordpress.com/2010/11/cqrs_documents.pdf) Янга про CQRS:

> One important aspect of Commands is that they are always in the **imperative** tense; that is they are telling the Application Server **to do something**. The linguistics with Commands are important. [...] Placing Commands in the imperative tense linguistically shows that the Application Server is allowed to reject the Command, if it were not allowed to, it would be an Event

Как еще одно доказательство. Если мы зашлем какую-нибудь _неизвестную команду_, она не будет выполнена (вылетит исключение) и обработка встанет.

> трактовал это как запись в логе о произошедшей в мастер-системе операции

Запись в логе о произошедшей в мастер-системе операции - это как раз Event, точнее даже Domain Event. В терминологии библиотеки `NuClear.OperationsTracking` - это `TrackedUseCase`. 

В отличие от него, `XXXAggregateOperation` - это то, что возникает на _primary_-стадии уже в репликации, и это как раз **команда**, которую нужно выполнить на _final_-стадии. И ее мастер-система - уже _River_.

Поэтому я и поднял вопрос об именовании, а главное - _о понимании_, этих сущностей в соотвествии в общепринятой терминологией.

**Comment by rechkalov** [comment]
До сих пор это была "операция, которая произошла", о чём и говорило название. Если ты хочешь сменить семантику на "команда, которая должна быть выполнена" - мы можем обсудить это на планировании.

**Comment by denisivan0v** [comment]
Отложим активности по этой теме до следующей итерации. @maximpashuk, догоняй

**Comment by denisivan0v** [comment]
Issue solved by events and commands introduction in #71
